// <auto-generated />
using System;
using Aphant.Impl.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Aphant.Impl.Database.Migrations
{
    [DbContext(typeof(AphantasiaDataContext))]
    [Migration("20260427211500_ChatMessages")]
    partial class ChatMessages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Aphant.Impl.Database.Entity.BookmarkEntity", b =>
                {
                    b.Property<Guid>("ThoughtId")
                        .HasColumnType("uuid")
                        .HasColumnName("thought_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("ThoughtId", "UserId")
                        .HasName("pk_bookmarks");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_bookmarks_user_id");

                    b.ToTable("bookmarks", (string)null);
                });

            modelBuilder.Entity("Aphant.Impl.Database.Entity.ChatMessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<double>("PositionX")
                        .HasColumnType("double precision")
                        .HasColumnName("position_x");

                    b.Property<double>("PositionY")
                        .HasColumnType("double precision")
                        .HasColumnName("position_y");

                    b.HasKey("Id")
                        .HasName("pk_chat_messages");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_chat_messages_author_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_chat_messages_created_at");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_chat_messages_parent_id");

                    b.ToTable("chat_messages", (string)null);
                });

            modelBuilder.Entity("Aphant.Impl.Database.Entity.ConceptEntity", b =>
                {
                    b.Property<string>("Tag")
                        .HasColumnType("text")
                        .HasColumnName("tag");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created");

                    b.HasKey("Tag")
                        .HasName("pk_concepts");

                    b.ToTable("concepts", (string)null);
                });

            modelBuilder.Entity("Aphant.Impl.Database.Entity.ConceptFollowEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("ConceptTag")
                        .HasColumnType("text")
                        .HasColumnName("concept_tag");

                    b.Property<int>("MinimumReplies")
                        .HasColumnType("integer")
                        .HasColumnName("minimum_replies");

                    b.HasKey("UserId", "ConceptTag")
                        .HasName("pk_concept_follows");

                    b.HasIndex("ConceptTag")
                        .HasDatabaseName("ix_concept_follows_concept_tag");

                    b.ToTable("concept_follows", (string)null);
                });

            modelBuilder.Entity("Aphant.Impl.Database.Entity.EpochEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.HasKey("Id")
                        .HasName("pk_epochs");

                    b.ToTable("epochs", (string)null);
                });

            modelBuilder.Entity("Aphant.Impl.Database.Entity.NotificationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created");

                    b.Property<Guid?>("FromUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_user_id");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<string>("Text")
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<Guid?>("ThoughtId")
                        .HasColumnType("uuid")
                        .HasColumnName("thought_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("FromUserId")
                        .HasDatabaseName("ix_notifications_from_user_id");

                    b.HasIndex("ThoughtId")
                        .HasDatabaseName("ix_notifications_thought_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_notifications_user_id");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("Aphant.Impl.Database.Entity.ThoughtConceptEntity", b =>
                {
                    b.Property<Guid>("ThoughtId")
                        .HasColumnType("uuid")
                        .HasColumnName("thought_id");

                    b.Property<string>("ConceptTag")
                        .HasColumnType("text")
                        .HasColumnName("concept_tag");

                    b.HasKey("ThoughtId", "ConceptTag")
                        .HasName("pk_thought_concepts");

                    b.HasIndex("ConceptTag")
                        .HasDatabaseName("ix_thought_concepts_concept_tag");

                    b.ToTable("thought_concepts", (string)null);
                });

            modelBuilder.Entity("Aphant.Impl.Database.Entity.ThoughtEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)")
                        .HasColumnName("content");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created");

                    b.Property<int?>("EpochId")
                        .HasColumnType("integer")
                        .HasColumnName("epoch_id");

                    b.Property<double>("PositionX")
                        .HasColumnType("double precision")
                        .HasColumnName("position_x");

                    b.Property<double>("PositionY")
                        .HasColumnType("double precision")
                        .HasColumnName("position_y");

                    b.Property<int>("Shape")
                        .HasColumnType("integer")
                        .HasColumnName("shape");

                    b.Property<int>("SizeMultiplier")
                        .HasColumnType("integer")
                        .HasColumnName("size_multiplier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_thoughts");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_thoughts_author_id");

                    b.HasIndex("DateCreated")
                        .HasDatabaseName("ix_thoughts_date_created");

                    b.HasIndex("EpochId")
                        .HasDatabaseName("ix_thoughts_epoch_id");

                    b.ToTable("thoughts", (string)null);
                });

            modelBuilder.Entity("Aphant.Impl.Database.Entity.ThoughtReferenceEntity", b =>
                {
                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.HasKey("SourceId", "TargetId")
                        .HasName("pk_thought_references");

                    b.HasIndex("TargetId")
                        .HasDatabaseName("ix_thought_references_target_id");

                    b.ToTable("thought_references", (string)null);
                });

            modelBuilder.Entity("Aphant.Impl.Database.Entity.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("bio");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color");

                    b.Property<DateTime>("DateJoined")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_joined");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("email");

                    b.Property<string>("PassHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("pass_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Aphant.Impl.Database.Entity.UserFollowEntity", b =>
                {
                    b.Property<Guid>("FollowedId")
                        .HasColumnType("uuid")
                        .HasColumnName("followed_id");

                    b.Property<Guid>("FollowerId")
                        .HasColumnType("uuid")
                        .HasColumnName("follower_id");

                    b.HasKey("FollowedId", "FollowerId")
                        .HasName("pk_user_follows");

                    b.HasIndex("FollowerId")
                        .HasDatabaseName("ix_user_follows_follower_id");

                    b.ToTable("user_follows", (string)null);
                });

            modelBuilder.Entity("Aphant.Impl.Database.Entity.BookmarkEntity", b =>
                {
                    b.HasOne("Aphant.Impl.Database.Entity.ThoughtEntity", "Thought")
                        .WithMany("Bookmarks")
                        .HasForeignKey("ThoughtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bookmarks_thoughts_thought_id");

                    b.HasOne("Aphant.Impl.Database.Entity.UserEntity", "User")
                        .WithMany("Bookmarks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bookmarks_users_user_id");

                    b.Navigation("Thought");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Aphant.Impl.Database.Entity.ChatMessageEntity", b =>
                {
                    b.HasOne("Aphant.Impl.Database.Entity.UserEntity", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_messages_users_author_id");

                    b.HasOne("Aphant.Impl.Database.Entity.ChatMessageEntity", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_chat_messages_chat_messages_parent_id");

                    b.Navigation("Author");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Aphant.Impl.Database.Entity.ConceptFollowEntity", b =>
                {
                    b.HasOne("Aphant.Impl.Database.Entity.ConceptEntity", "Concept")
                        .WithMany()
                        .HasForeignKey("ConceptTag")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_concept_follows_concepts_concept_tag");

                    b.HasOne("Aphant.Impl.Database.Entity.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_concept_follows_users_user_id");

                    b.Navigation("Concept");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Aphant.Impl.Database.Entity.NotificationEntity", b =>
                {
                    b.HasOne("Aphant.Impl.Database.Entity.UserEntity", "FromUser")
                        .WithMany()
                        .HasForeignKey("FromUserId")
                        .HasConstraintName("fk_notifications_users_from_user_id");

                    b.HasOne("Aphant.Impl.Database.Entity.ThoughtEntity", "Thought")
                        .WithMany("Notifications")
                        .HasForeignKey("ThoughtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_notifications_thoughts_thought_id");

                    b.HasOne("Aphant.Impl.Database.Entity.UserEntity", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_users_user_id");

                    b.Navigation("FromUser");

                    b.Navigation("Thought");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Aphant.Impl.Database.Entity.ThoughtConceptEntity", b =>
                {
                    b.HasOne("Aphant.Impl.Database.Entity.ConceptEntity", "Concept")
                        .WithMany()
                        .HasForeignKey("ConceptTag")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_thought_concepts_concepts_concept_tag");

                    b.HasOne("Aphant.Impl.Database.Entity.ThoughtEntity", "Thought")
                        .WithMany()
                        .HasForeignKey("ThoughtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_thought_concepts_thoughts_thought_id");

                    b.Navigation("Concept");

                    b.Navigation("Thought");
                });

            modelBuilder.Entity("Aphant.Impl.Database.Entity.ThoughtEntity", b =>
                {
                    b.HasOne("Aphant.Impl.Database.Entity.UserEntity", "Author")
                        .WithMany("Thoughts")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_thoughts_users_author_id");

                    b.HasOne("Aphant.Impl.Database.Entity.EpochEntity", "Epoch")
                        .WithMany("Thoughts")
                        .HasForeignKey("EpochId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_thoughts_epochs_epoch_id");

                    b.Navigation("Author");

                    b.Navigation("Epoch");
                });

            modelBuilder.Entity("Aphant.Impl.Database.Entity.ThoughtReferenceEntity", b =>
                {
                    b.HasOne("Aphant.Impl.Database.Entity.ThoughtEntity", "SourceThought")
                        .WithMany("Links")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_thought_references_thoughts_source_id");

                    b.HasOne("Aphant.Impl.Database.Entity.ThoughtEntity", "TargetThought")
                        .WithMany("Backlinks")
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_thought_references_thoughts_target_id");

                    b.Navigation("SourceThought");

                    b.Navigation("TargetThought");
                });

            modelBuilder.Entity("Aphant.Impl.Database.Entity.UserFollowEntity", b =>
                {
                    b.HasOne("Aphant.Impl.Database.Entity.UserEntity", "Followed")
                        .WithMany()
                        .HasForeignKey("FollowedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_follows_users_followed_id");

                    b.HasOne("Aphant.Impl.Database.Entity.UserEntity", "Follower")
                        .WithMany()
                        .HasForeignKey("FollowerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_follows_users_follower_id");

                    b.Navigation("Followed");

                    b.Navigation("Follower");
                });

            modelBuilder.Entity("Aphant.Impl.Database.Entity.EpochEntity", b =>
                {
                    b.Navigation("Thoughts");
                });

            modelBuilder.Entity("Aphant.Impl.Database.Entity.ThoughtEntity", b =>
                {
                    b.Navigation("Backlinks");

                    b.Navigation("Bookmarks");

                    b.Navigation("Links");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("Aphant.Impl.Database.Entity.UserEntity", b =>
                {
                    b.Navigation("Bookmarks");

                    b.Navigation("Notifications");

                    b.Navigation("Thoughts");
                });
#pragma warning restore 612, 618
        }
    }
}
