// <auto-generated />
using System;
using Aphant.Impl.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Aphant.Impl.Database.Migrations
{
    [DbContext(typeof(AphantasiaDataContext))]
    [Migration("20260208014711_DateJoined")]
    partial class DateJoined
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Aphant.Impl.Database.Entity.BookmarkEntity", b =>
                {
                    b.Property<Guid>("ThoughtId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("ThoughtId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookmarks");
                });

            modelBuilder.Entity("Aphant.Impl.Database.Entity.ConceptEntity", b =>
                {
                    b.Property<string>("Tag")
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Tag");

                    b.ToTable("Concepts");
                });

            modelBuilder.Entity("Aphant.Impl.Database.Entity.ConceptFollowEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConceptTag")
                        .HasColumnType("text");

                    b.Property<int>("MinimumReplies")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "ConceptTag");

                    b.HasIndex("ConceptTag");

                    b.ToTable("ConceptFollows");
                });

            modelBuilder.Entity("Aphant.Impl.Database.Entity.EpochEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Epochs");
                });

            modelBuilder.Entity("Aphant.Impl.Database.Entity.NotificationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.Property<Guid?>("ThoughtId")
                        .HasColumnType("uuid");

                    b.Property<byte>("Type")
                        .HasColumnType("smallint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ThoughtId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Aphant.Impl.Database.Entity.ThoughtConceptEntity", b =>
                {
                    b.Property<Guid>("ThoughtId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConceptTag")
                        .HasColumnType("text");

                    b.HasKey("ThoughtId", "ConceptTag");

                    b.HasIndex("ConceptTag");

                    b.ToTable("ThoughtConcepts");
                });

            modelBuilder.Entity("Aphant.Impl.Database.Entity.ThoughtEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EpochId")
                        .HasColumnType("uuid");

                    b.Property<double>("PositionX")
                        .HasColumnType("double precision");

                    b.Property<double>("PositionY")
                        .HasColumnType("double precision");

                    b.Property<byte>("Shape")
                        .HasColumnType("smallint");

                    b.Property<int>("SizeMultiplier")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("DateCreated");

                    b.HasIndex("EpochId");

                    b.ToTable("Thoughts");
                });

            modelBuilder.Entity("Aphant.Impl.Database.Entity.ThoughtReferenceEntity", b =>
                {
                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid");

                    b.HasKey("SourceId", "TargetId");

                    b.HasIndex("TargetId");

                    b.ToTable("ThoughtReferences");
                });

            modelBuilder.Entity("Aphant.Impl.Database.Entity.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateJoined")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Aphant.Impl.Database.Entity.UserFollowEntity", b =>
                {
                    b.Property<Guid>("FollowedId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FollowerId")
                        .HasColumnType("uuid");

                    b.HasKey("FollowedId", "FollowerId");

                    b.HasIndex("FollowerId");

                    b.ToTable("UserFollows");
                });

            modelBuilder.Entity("Aphant.Impl.Database.Entity.BookmarkEntity", b =>
                {
                    b.HasOne("Aphant.Impl.Database.Entity.ThoughtEntity", "Thought")
                        .WithMany("Bookmarks")
                        .HasForeignKey("ThoughtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aphant.Impl.Database.Entity.UserEntity", "User")
                        .WithMany("Bookmarks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Thought");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Aphant.Impl.Database.Entity.ConceptFollowEntity", b =>
                {
                    b.HasOne("Aphant.Impl.Database.Entity.ConceptEntity", "Concept")
                        .WithMany()
                        .HasForeignKey("ConceptTag")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aphant.Impl.Database.Entity.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Concept");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Aphant.Impl.Database.Entity.NotificationEntity", b =>
                {
                    b.HasOne("Aphant.Impl.Database.Entity.ThoughtEntity", "Thought")
                        .WithMany()
                        .HasForeignKey("ThoughtId");

                    b.HasOne("Aphant.Impl.Database.Entity.UserEntity", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Thought");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Aphant.Impl.Database.Entity.ThoughtConceptEntity", b =>
                {
                    b.HasOne("Aphant.Impl.Database.Entity.ConceptEntity", "Concept")
                        .WithMany()
                        .HasForeignKey("ConceptTag")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aphant.Impl.Database.Entity.ThoughtEntity", "Thought")
                        .WithMany()
                        .HasForeignKey("ThoughtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Concept");

                    b.Navigation("Thought");
                });

            modelBuilder.Entity("Aphant.Impl.Database.Entity.ThoughtEntity", b =>
                {
                    b.HasOne("Aphant.Impl.Database.Entity.UserEntity", "Author")
                        .WithMany("Thoughts")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aphant.Impl.Database.Entity.EpochEntity", "Epoch")
                        .WithMany("Thoughts")
                        .HasForeignKey("EpochId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Author");

                    b.Navigation("Epoch");
                });

            modelBuilder.Entity("Aphant.Impl.Database.Entity.ThoughtReferenceEntity", b =>
                {
                    b.HasOne("Aphant.Impl.Database.Entity.ThoughtEntity", "SourceThought")
                        .WithMany("Links")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aphant.Impl.Database.Entity.ThoughtEntity", "TargetThought")
                        .WithMany("Backlinks")
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceThought");

                    b.Navigation("TargetThought");
                });

            modelBuilder.Entity("Aphant.Impl.Database.Entity.UserFollowEntity", b =>
                {
                    b.HasOne("Aphant.Impl.Database.Entity.UserEntity", "Followed")
                        .WithMany()
                        .HasForeignKey("FollowedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aphant.Impl.Database.Entity.UserEntity", "Follower")
                        .WithMany()
                        .HasForeignKey("FollowerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Followed");

                    b.Navigation("Follower");
                });

            modelBuilder.Entity("Aphant.Impl.Database.Entity.EpochEntity", b =>
                {
                    b.Navigation("Thoughts");
                });

            modelBuilder.Entity("Aphant.Impl.Database.Entity.ThoughtEntity", b =>
                {
                    b.Navigation("Backlinks");

                    b.Navigation("Bookmarks");

                    b.Navigation("Links");
                });

            modelBuilder.Entity("Aphant.Impl.Database.Entity.UserEntity", b =>
                {
                    b.Navigation("Bookmarks");

                    b.Navigation("Notifications");

                    b.Navigation("Thoughts");
                });
#pragma warning restore 612, 618
        }
    }
}
